from sqlalchemy import create_engine, Column, String, Integer, DateTime, Text, JSON, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship
from datetime import datetime

Base = declarative_base()

class User(Base):
    """User table storing Telegram user information."""
    __tablename__ = 'users'
    
    id = Column(Integer, primary_key=True)
    telegram_id = Column(String(50), unique=True, nullable=False)
    username = Column(String(100))
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    itineraries = relationship('Itinerary', back_populates='user')
    favorites = relationship('Favorite', back_populates='user')
    chat_logs = relationship('ChatLog', back_populates='user')

class Itinerary(Base):
    """Table storing travel itineraries generated by the bot."""
    __tablename__ = 'itineraries'
    
    id = Column(Integer, primary_key=True)
    telegram_id = Column(String(50), ForeignKey('users.telegram_id'))
    destination = Column(String(100), nullable=False)
    days = Column(Integer, nullable=False)
    budget = Column(String(50))
    interests = Column(Text)
    itinerary_data = Column(JSON)  # Stores the full plan as JSON
    created_at = Column(DateTime, default=datetime.utcnow)
    
    user = relationship('User', back_populates='itineraries')

class Favorite(Base):
    """Table storing places saved by users."""
    __tablename__ = 'favorites'
    
    id = Column(Integer, primary_key=True)
    telegram_id = Column(String(50), ForeignKey('users.telegram_id'))
    place_name = Column(String(200), nullable=False)
    place_type = Column(String(50))  # e.g., attraction, restaurant
    location = Column(String(200))
    notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    user = relationship('User', back_populates='favorites')

class ChatLog(Base):
    """Table logging conversation history for analytics."""
    __tablename__ = 'chat_logs'
    
    id = Column(Integer, primary_key=True)
    telegram_id = Column(String(50), ForeignKey('users.telegram_id'))
    message = Column(Text, nullable=False)
    response = Column(Text, nullable=False)
    feature_type = Column(String(50), nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    user = relationship('User', back_populates='chat_logs')
